on:
  push:
    branches: ["main"]
name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - run: GOPROXY=proxy.golang.org go list -m github.com/junitechnology/jpipe